### ISSUE TITLE
Multiple generators

### ISSUE THREAD

**Issue by magick93** [basilfx/xtext-standalone-maven-build#1]
Hello

This looks like a cool project! Thanks for sharing it.

Im interested in having multiple generators for a common metamodel. For example, if we were to use the Library example, one generator would produce JPA pojos, another would generate HTML.

What advice, or how would you recommend this project be structured to achieve the above?

**Comment by basilfx** [comment]
Hi @magick93,

I think this is outside the scope of this demonstration project. I think this is just part of Xtext itself: https://www.eclipse.org/forums/index.php/t/263021/.

You basically generate an additional generator, and register it.

Kind regards,
Bas

**Comment by magick93** [comment]
Ok, thanks @basilfx
